# Generated by Django 3.2.20 on 2023-08-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeeshoppost',
            options={'ordering': ['-created_on']},
        ),
    ]
