# Generated by Django 3.2.20 on 2023-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeposts', '0002_alter_coffeeshoppost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshoppost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='coffeeshoppost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
