# Generated by Django 3.2.20 on 2023-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeposts', '0003_auto_20230809_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshoppost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='coffeeshoppost',
            name='longitude',
        ),
        migrations.AddField(
            model_name='coffeeshoppost',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
