# Generated by Django 3.2.20 on 2023-08-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeposts', '0007_auto_20230809_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='created_on',
        ),
    ]
