# Generated by Django 3.2.20 on 2023-08-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeposts', '0009_auto_20230810_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshoppost',
            name='review',
            field=models.CharField(default='empty', max_length=600),
        ),
    ]
