# Generated by Django 3.2.20 on 2023-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeposts', '0010_coffeeshoppost_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshoppost',
            name='review',
            field=models.CharField(max_length=600),
        ),
    ]
