# Generated by Django 3.2.20 on 2023-08-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeposts', '0012_coffeeshoppost_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, '1 Star = Do not reccomend'), (2, '2 Star = Would visit if no other options'), (3, '3 Star = Not bad if you need a fix'), (4, '4 Star = They know what they are doing'), (5, '5 Star = Must try!')], default=0),
        ),
    ]
